vertica:
  host: "vertica-ce"  # to connect to host from wsl use "host.docker.internal"
  port: 5433
  user: "cognos"
  password: "admin1234"
  database: "vdb"
  pool_size: 5
  schema: "omniq"

xml_path:
  cdr_template: "config/cdrs_template.xml"  # Directory for CDR XML files
  fields_template: "config/fields_template.xml"  # Path to fields XML

yaml_path:
  columns: "config/columns/columns.yaml"  # Output for columns YAML
  tables: "config/tables"  # Directory for table YAML files

tables:
  - users
  - products
  - orders
  - CDR_HPA_SIP
  - CDR_HPA_DIAMETER

generate_rows: 1000

type_mapping:
  Float: DECIMAL(10,2)
  Integer: INTEGER
  Double: BIGINT
  String: VARCHAR(100)
  Long: NUMERIC(14,2)
  IP: VARCHAR(100)
  Binary: BINARY
  Short: SMALLINT
  "Time Stamp": TIMESTAMP
  Date: TIMESTAMP
  "Custom Field Item": VARCHAR(100)
  BigDouble: BIGINT
  Boolean: BOOLEAN

simulation_config:
  DECIMAL(10,2):
    type: random
    distribution: normal
    params:
      mean: 100.0
      std_dev: 25.0
      max: 99999999.99
      min: 0.01
  INTEGER:
    type: sequence
    start: 1000
    step: 1
  BIGINT:
    type: random
    distribution: uniform
    params:
      min: 0
      max: 1000000
  VARCHAR(100):
    type: random
    distribution: string
    params:
      length: 10
  NUMERIC(14,2):
    type: random
    distribution: normal
    params:
      mean: 5000.0
      std_dev: 1000.0
      max: 1000000.0
      min: 0.0
  BINARY:
    type: random
    distribution: binary
    params:
      length: 16
  SMALLINT:
    type: random
    distribution: uniform
    params:
      min: 0
      max: 100
  TIMESTAMP:
    type: random
    distribution: datetime
    params:
      start: "2023-01-01T00:00:00"
      end: "2023-12-31T23:59:59"

              # ┌───────────── minute (0 - 59)
              # │ ┌───────────── hour (0 - 23)
              # │ │ ┌───────────── day of month (1 - 31)
              # │ │ │ ┌───────────── month (1 - 12)
              # │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday=0)
              # │ │ │ │ │
              # * * * * * /usr/local/bin/python /app/your_script.py >> /var/log/cron.log 2>&1

cron_schedule: "*/5 * * * *"  # Example: Run every 5 minutes.
