apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-simulator.configmapName" . }}
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
data:
  {{ .Values.config.files.mainConfig | base }}: |-
    {{- .Files.Get (printf "files/%s" .Values.config.files.mainConfig) | nindent 4 }}
  {{- range $col := .Values.config.files.columns }}
  {{ $col | base }}: |-
    {{- $.Files.Get (printf "files/%s" $col) | nindent 4 }}
  {{- end }}
  {{- range $table := .Values.config.files.tables }}
  {{ $table | base }}: |-
    {{- $.Files.Get (printf "files/%s" $table) | nindent 4 }}
  {{- end }}
  {{- range $sql := .Values.config.files.sql }}
  {{ $sql | base }}: |-
    {{- $.Files.Get (printf "files/%s" $sql) | nindent 4 }}
  {{- end }}