apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-simulator.fullname" . }}
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "data-simulator.labels" . | nindent 8 }}
    spec:
       {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "data-simulator.fullname" . }}
        {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.config.mountFolders }}
              - name: config-volume
                mountPath: {{ .Values.config.folderPaths.config }}
                readOnly: true
              - name: config-volume
                mountPath: {{ .Values.config.folderPaths.sql }}
                subPath: sql
                readOnly: true
          {{- else }}
            {{- include "data-simulator.configVolumeMounts" . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "data-simulator.fullname" . }}-config
            {{- if .Values.config.mountFolders }}
            items:
              - key: columns/
                path: columns/
              - key: tables/
                path: tables/
              - key: config.yaml
                path: config.yaml
            {{- end }}
      metadata:
        annotations:
          checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            
