{{- if and .Values.storage.config.enabled (not .Values.storage.useHostPath) (not .Values.storage.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "data-simulator.fullname" . }}-config
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.config.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
  {{- if .Values.storage.config.storageClass }}
  storageClassName: {{ .Values.storage.config.storageClass }}
  {{- end }}
{{- end }}

{{- if and .Values.storage.columns.enabled (not .Values.storage.useHostPath) (not .Values.storage.columns.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "data-simulator.fullname" . }}-columns
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.columns.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.columns.size }}
  {{- if .Values.storage.columns.storageClass }}
  storageClassName: {{ .Values.storage.columns.storageClass }}
  {{- end }}
{{- end }}

{{- if and .Values.storage.tables.enabled (not .Values.storage.useHostPath) (not .Values.storage.tables.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "data-simulator.fullname" . }}-tables
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.tables.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.tables.size }}
  {{- if .Values.storage.tables.storageClass }}
  storageClassName: {{ .Values.storage.tables.storageClass }}
  {{- end }}
{{- end }}