apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-simulator.fullname" . }}
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}