# Default values for data-simulator
app:
  replicaCount: 1
  image:
    repository: prk327/data_simulator
    tag: v1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: PYTHONUNBUFFERED
      value: "1"

# Config Files
config:
  enabled: true
  files:
    mainConfig: config/config.yaml
    columns:
      - config/columns/columns.yaml
    tables:
      - config/tables/CDR_GN.yaml
      - config/tables/CDR_S1AP.yaml
    # sql:
    #   - sql/delete.sql
    #   - sql/insert.sql
    #   - sql/read.sql
    #   - sql/update.sql
  # Mount entire folders instead of individual files
  mountFolders: false
  folderPaths:
    config: /app/config
    sql: /app/sql

# Service Configuration
service:
  type: ClusterIP
  port: 8000

# Ingress Configuration (optional)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: data-simulator.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""