columns:
- TIME_STAMP
- MEASURING_PROBE_LOC_ID
- PROBE_ID
- MEASURING_PROBE_NAME
- MEASURING_PROBE_TYPE
- QMANAGER_TIME_STAMP
- NUM_OF_TRANSACTIONS
- SESSION_ID
- INTERFACE
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- END_CAUSE
- SIGNALING_FILE_NAME
- DIRECTION
- SOURCE_IP
- DEST_IP
- TOTAL_DL_SIGNALING_BYTES
- TOTAL_UL_SIGNALING_BYTES
- AMF_IP_ADDRESS
- GNB_IP_ADDRESS
- TRANSPORT_LAYER_ADDRESS_DL
- TRANSPORT_LAYER_ADDRESS_UL
- GTP_TEID_DL
- GTP_TEID_UL
- AMF_UE_ID
- GNB_UE_ID
- IMSI
- SUPI
- SUCI
- MCC
- MNC
- MCC_MNC
- APN
- BEARER_QCI
- NSSAI_SST
- NSSAI_SD
- CGI
- SERV_PRO_CORRELATION_ID
- RELEASE_CAUSE
- AMF_NAME
- GNB_NAME
- CELL_NAME
- CELL_REGION
- APN_SERVICE
- RAT_TYPE_NAME
- SOURCE_NE_NAME
- DEST_NE_NAME
- FRAMES_COUNT
- UNIQUE_CDR_ID
- NAS_5GMM_CAUSE
- NAS_5GSM_CAUSE
- FIRST_PROCEDURE_TYPE
- NGAP_PROCEDURES_LIST
- NGAP_AMF_NAME
- IMEI
- IMEI_SV
- VLAN_ID
- RETAINABILITY_KPI
- ACCESSIBILITY_KPI
- MOBILITY_KPI
- NGAP_ENCRYPTED_ALGORITHM
- CIPHERED_FRAMES
- DECIPHERED_FRAMES
- FAILED_DECIPHERING_FRAMES
- GUTI
- OLD_GUTI
- GUTI_LIST
- TEID_AND_IP_LIST
- RES
- RAND
- AUTN
- IMSI_CORRELATION_KEY
- MSISDN
- SOURCE_UE_ID_LIST
- AMF_UE_NGAP_ID_LIST
- RAN_UE_NGAP_ID_LIST
- TAI_TAC_COUNT
- HANDOVER_NUMBER
- CGI_COUNT
- CGI_LIST
- FIRST_CGI
- LAST_CGI_TIMESTAMP
- HANDOVER_COUNT
- PAGING_DURATION
- PAGING_BULK_COUNT
- TARGET_CELL_ID
- TARGET_C_ID
- TARGET_LAC
- GTP_TEID_UL_OLD
- GTP_TEID_DL_OLD
- TUNNEL_ID_CONTROL_UPLINK
- TUNNEL_ID_CONTROL_DOWNLINK
- TUNNEL_ID_DATA_UPLINK
- TUNNEL_ID_DATA_DOWNLINK
- BEARER_QCI_LIST
- NGAP_REGI_REQUEST_TIMESTAMP
- NGAP_REGI_ACCEPT_TIMESTAMP
- NGAP_REGI_COMPLETE_TIMESTAMP
- NGAP_REGI_REJECT_TIMESTAMP
- NGAP_DEREGI_REQUEST_TIMESTAMP
- NGAP_DEREGI_ACCEPT_TIMESTAMP
- NGAP_DEREGI_COMPLETE_TIMESTAMP
- NGAP_DEREGI_REJECT_TIMESTAMP
- NGAP_SERVICE_REQUEST_TIMESTAMP
- NGAP_SERVICE_REJECT_TIMESTAMP
- NGAP_SERVICE_ACCEPT_TIMESTAMP
- NGAP_AUTH_REQUEST_TIMESTAMP
- NGAP_AUTH_RESPONSE_TIMESTAMP
- NGAP_AUTH_REJECT_TIMESTAMP
- NGAP_AUTH_FAILURE_TIMESTAMP
- NGAP_AUTH_RESULT_TIMESTAMP
- NGAP_SESS_ESTAB_REQ_TIMESTAMP
- NGAP_SESS_ESTAB_ACC_TIMESTAMP
- NGAP_SESS_ESTAB_REJ_TIMESTAMP
- NGAP_PROCEDURE_KPIS_LIST
- TOTAL_NAS
- TOTAL_NAS_DECODED
- NGAP_CAUSE_LIST
- RAT_TYPE
- FRAMES_COUNT_SAVED
- MS_IP_ADDRESS
- APN_LIST
- END_TIME
- REG_TYPE_5GS
table_name: CDR_NGAP
