columns:
- TIME_STAMP
- SOURCE_ALIAS_FULL
- DEST_ALIAS_FULL
- SIGNALING_FILE_NAME
- USER_PLANE_FILE_NAME
- RTP_DST_IP
- RTP_SRC_IP
- IMSI
- MSISDN
- DEST_IP
- SOURCE_IP
- OPEN_SESSION_IDS
- RELEASE_CAUSE
- CALL_STATE
- RTP_INITIAL
- CORRELATION_PROTOCOLS
- CORRELATION_SESSION_IDS
- START_TIME
- SERV_PRO_CORRELATION_ID
- ASR
- NER
- TOTAL_SUCCESS_CALL
- TOTAL_CALL_ATTEMPTS
- ORIG_CALL_ID
- TERM_CALL_ID
- ORIG_FWD_CONTACT_URI_USER
- ORIG_SIP_REASON
- TERM_SIP_REASON
- IMS_CHARGING_ID
- DIVERSION
- DIVERSION_REASON
- DISCONNECTION_TIME_TERM
- ORIG_SETUP_TIME
- CALLED_PARTY
- CALLING_PARTY
- ORIG_PDD
- IN_SSRC
- OUT_SSRC
- NUM_OF_TRANSACTIONS
- CALL_DURATION
- SIP_RELEASE_CAUSE
- MASTER_SESSION_TYPE
- PROCEDURE_DURATION
- ORIGINATING_MS_IP_ADDRESS
- TERMINATING_MS_IP_ADDRESS
- JITTER_AVG
- PASSIVE_MOS_AVG
- PMOS_RFACTOR_AVG
- PACKET_LOSS_RATE
- MSG_COUNT
- CORRELATION_PROCEDURES
- CORRELATION_PROBE_IDS
- TERM_P_ACCESS_NETWORK_INFO
- ORIGINATING_PATH
- TERMINATING_PATH
- UNIQUE_CDR_ID
- MCPTT_GRANTED_PARTY_ID
- MCPTT_PARTY_ID
- MCPTT_GROUP_ID
- RTCP_METADATA
- DIVERSION_TIME_STAMP
- RTP_CODECS_LIST
- MEDIA_TYPE
- MC_SERVICE
- TOTAL_RTP_ONE_WAY_COUNT
- SIP_EVENT_HEADER
- SOURCE_NE_NAME
- DEST_NE_NAME
- PASSERTED_IDENTITY_LIST
- PDD
- CALLED_COUNTRY_CODE
- CALLING_COUNTRY_CODE
table_name: CDR_MASTER_SESSION_COMPOSITE
