columns:
- TIME_STAMP
- MEASURING_PROBE_NAME
- SESSION_ID
- APN
- IMSI
- MCC
- MNC
- MS_IP_ADDRESS
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- FRAMES_COUNT
- MSISDN
- SGSN_NAME_SIGNALING
- GGSN_NAME_SIGNALING
- CHARGING_ID
- CHARGING_TYPE
- SIGNALING_FILE_NAME
- IMEI
- IMEI_SV
- RAT_TYPE
- CGI
- TAC
- END_TIME
- SOURCE_IP
- DEST_IP
- TUNNEL_ID_CONTROL_UPLINK
- TUNNEL_ID_CONTROL_DOWNLINK
- TUNNEL_ID_DATA_UPLINK
- TUNNEL_ID_DATA_DOWNLINK
- SGW_NAME_SIGNALING
- PGW_NAME_SIGNALING
- MME_NAME
- BEARER_QCI
- BEARER_ID
- SERV_PRO_CORRELATION_ID
- RELEASE_CAUSE
- MANUFACTURER
- MODEL
- CELL_NAME
- GTP_TEID_DL
- GTP_TEID_UL
- GTP_TEID_UL_OLD
- GTP_TEID_DL_OLD
- APN_SERVICE
- TAC_CATEGORY
- CELL_REGION
- GTP_INTERFACE_TYPE
- GUTI
- STN_SR
- RAT_TYPE_NAME
- SOURCE_NE_NAME
- DEST_NE_NAME
- MSC_NAME
- PROCEDURE_SUBTYPE
- TAI_TAC
- EPDG_NAME_SIGNALING
- UNIQUE_CDR_ID
- MBMS_GW_NAME
- TMGI
- GBR_QCI
- MBMS_MULTICAST_DEST_IP_ADDR
- MBMS_MULTICAST_SRC_IP_ADDR
- TMGI_HEX
- FRAMES_COUNT_SAVED
table_name: CDR_GN
