columns:
- CDR_ID
- SESSION_ID
- NUM_OF_TRANSACTIONS
- PROCEDURE_TYPE
- INTERFACE
- START_TIME
- PROCEDURE_DURATION
- CIC
- DPC
- OPC
- OPC_SUBSRV
- DPC_SUBSRV
- CALLED_PARTY
- CALLING_PARTY
- CALLED_PARTY_PREF
- CALLING_PARTY_PREF
- CALLED_COUNTRY_CODE
- CALLING_COUNTRY_CODE
- SOURCE_PHONE_NUMBER
- DEST_PHONE_NUMBER
- ISUP_SERVICE_TYPE
- EVENT_TYPE
- END_CAUSE
- SIGNALING_FILE_NAME
- ISUP_ADDRESS_COMPLETE
- ISUP_ANSWER
- ISUP_CALL_PROGRESS
- ISUP_CONNECT
- ISUP_RELEASE
- ISUP_RELEASE_COMPLETE
- MEASURING_PROBE_NAME
- DPC_DECIMAL
- OPC_DECIMAL
- CALLED_NATURE
- CALLING_NATURE
- CALL_TYPE
- ISUP_IAM
- SETUP_TIME
- CALLED_NUMBERING_PLAN
- CALLED_NUMBER_PRESENTATION
- CALLING_NUMBERING_PLAN
- CALLING_NUMBER_PRESENTATION
- GENERIC_NUMBER
- GENERIC_ADDRESS_NATURE
- ORIGINAL_CALLED_NUMBER
- ORIGINAL_CALLED_NUMBER_PREF
- ORIGINAL_ADDRESS_NATURE
- REDIRECTION_NUMBER
- ISUP_RESUME
- ISUP_SUSPEND
- RELEASE_LOCATION
- REDIRECTION_IND
- ORG_REDIRECT_REASON
- REDIRECT_REASON
- TOTAL_CALL_ATTEMPTS
- PGAD
- ASR
- CALL_DURATION
- NER
- PDD
- OSLS
- DSLS
- TOTAL_SUCCESS_CALL
- PROBE_CORRELATION_ID
- VARIANT
- SIGNALING_LINK_KEY
- FULL_CDR
- MSU_COUNT
- OCTETS_COUNT
- END_TIME
- PROBE_GROUP_ID
- CHARGE
- DEST_IP
- DEST_IP_PORT
- SOURCE_IP
- SOURCE_IP_PORT
- TOTAL_ANSWERED_CALL
- RELEASE_CAUSE
- ROAMING_OPERATOR_NAME
- ROAMING_DIRECTION
- ROAMING_STATUS
- CALLING_PARTY_SUFFIX
- ORIGINAL_CALLED_NUMBER_SUFFIX
- RELEASED_BY
- SUB_SERVICE_INDICATOR
- FILTERED_SOURCE_IP
- FILTERED_DEST_IP
- ISUP_CHARGE_INFORMATION
- ISUP_FACILITY_ACCEPTED
- ISUP_FACILITY_REJECT
- ISUP_FACILITY_REQUEST
- DUALSEIZURE
- SERV_PRO_CORRELATION_ID
- REDIRECTING_NUMBER
- REDIRECTING_REASON
- PRESENTATION_ALLOWED
- CALLING_NUM_OF_DIGITS
- CALLED_NUM_OF_DIGITS
- CHARGE_NUMBER
- DEST_NE_NAME
- SOURCE_NE_NAME
- FRAMES_COUNT_SAVED
primary_key: CDR_ID
table_name: CDR_CN_ISUP
