columns:
- TIME_STAMP
- MEASURING_PROBE_LOC_ID
- PROBE_ID
- MEASURING_PROBE_NAME
- MEASURING_PROBE_TYPE
- QMANAGER_TIME_STAMP_OLD
- NUM_OF_TRANSACTIONS
- SESSION_ID_OLD
- RAN_PROBE_IP
- VCU_IP
- START_TIME
- PROCEDURE_COMPLETION
- X2_TIME_DUR_REQ_TO_RESP
- X2_TIME_DUR_REQ_TO_TRAN
- X2_TIME_DURATION_TOTAL
- RAN_SIGNALING_FILE_NAME
- X2_HDR_SOURCE_ENB_ID
- X2_HDR_SOURCE_ECGI
- X2_HDR_DESTINATION_ENB_ID
- X2_HDR_DESTINATION_ECGI
- X2_HDR_ENB_S1AP_ID
- X2_HDR_MME_S1AP_ID
- X2_HDR_FULL_GUMMEI
- IMSI
- IMEI
- X2_REQ_OLD_X2AP_ID
- X2_REQACK_NEW_X2AP_ID
- X2_REQ_HO_CAUSE
- X2_REQ_UE_SECURITY_CAP
- X2_REQ_ERAB_TOBESETUP_ID
- X2_REQ_ERAB_LEVEL_QOS_QCI
- X2_REQACK_ERAB_ADMITTED_ID
- X2_REQ_HO_RESTRICLIST
- X2_REQ_ALLOC_RET_PR_LVL
- X2_REQ_HIST_VISITED_CELL
- X2_REQ_HIST_TIME_ON_CELL
- X2_REQACK_MCI_TARGET_PCI
- X2_REQACK_MCI_CRR_DL_FREQ
- X2_REQACK_MCI_CRR_UL_FREQ
- X2_REQACK_MCI_CRR_BDW
- X2_REQACK_MCI_T304
- X2_REQACK_HO_TYPE
- X2_REQACK_ST_TR_ERAB_ID
- X2_ST_TR_OLD_X2AP_ID
- X2_ST_TR_NEW_X2AP_ID
- X2_ST_TR_ERAB_ID
- X2_RLS_CONT_OLD_X2AP_ID
- X2_RLS_CONT_NEW_X2AP_ID
- PROCEDURE_CODE
- GNB_REQ_ADDREQLST_QCI
- MENBTOSGNB_CAND_CELL_COUNT
- MENBTOSGNB_CAND_CELL_PCI
- MENBTOSGNB_CAND_CELL_RSRP
- SGNBTOMENB_SERVING_PCI
- SGNBTOMENB_SERVING_BAND_NR
- SGNBTOMENB_SERVING_FREQ_NR
- SGNBTOMENB_SERVING_CBW
- GNB_CID
- SGNBINITSGNBMOD_REASON
- SGNB_NOTIFICATION_REASON
- SGNBINIT_RLS_CAUSE
- SCG_FAILURE_INFORMATION_NR
- X2_SGNBTOMENB_GNB_NCGI
- MENBTOSGNB_CAND_CELL_FREQ
- SGNB_ADDITION_REJECT_CAUSE
- RELEASE_CAUSE
- SOURCE_NE_NAME
- DEST_NE_NAME
- HO_TRIGGER_COUNT
- HO_TO_PCI
- NEIGHBOR_PCI
- SERVING_CELL_RSRP_DBM
- NEIGHBOR_CELL_RSRP_DBM
- SERVING_CELL_RSRQ_DB
- NEIGHBOR_CELL_RSRQ_DB
- HO_DRTION_FRST_TRGGR_TO_ACTION
- HO_DRTION_LST_TRGGR_TO_ACTION
- BEARER_QCI_STRING
- QOSFLOW_FIVEQI
- SOURCE_BAND_NR
- TIME_ON_LAST_CELLS
- NSSAI
- UNIQUE_CDR_ID
table_name: CDR_RRC_X2_LTE
