columns:
- TIME_STAMP
- MEASURING_PROBE_NAME
- SESSION_ID
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- END_CAUSE
- IMSI
- MCC
- MNC
- MCC_MNC
- LAC
- CGI
- CELL_ID
- RAC
- P_TMSI
- TMSI
- MSISDN
- SIGNALING_FILE_NAME
- NON_GPRS_DETACH_TYPE
- OPC
- DPC
- CALLED_SSN
- CALLING_SSN
- SCCP_CALLED_NUMBER
- ORIGINAL_CALLED_NUMBER
- SCCP_CALLING_NUMBER
- ROAMING_NUMBER
- REROUTING_NUMBER
- SERVICE_KEY
- CALLED_PARTY
- CALLING_PARTY
- IMEI
- CALL_TYPE
- END_TIME
- HLR_NUMBER
- VLR_NUMBER
- MSC_NUMBER
- SC_ADDRESS
- SGSN_ADDRESS_SIGNALING
- APN
- USSD_STRING
- ROAMING_DIRECTION
- RELEASE_CAUSE
- SERV_PRO_CORRELATION_ID
- SGSN_NUMBER
- GSMSCF_NUMBER
- EIR_NUMBER
- HANDOVER_NUMBER
- UNIQUE_CDR_ID
- FORWARDED_TO_NUMBER
- MSG_COUNT
- CORRELATION_PROCEDURES
- CALL_DURATION
- TCAP_SESSION_ERROR_CODES
- SOURCE_NE_NAME
- DEST_NE_NAME
- FRAMES_COUNT_SAVED
# primary_key: SESSION_ID_OLD
table_name: CDR_CN
