columns:
- TIME_STAMP
- MEASURING_PROBE_NAME
- SESSION_ID
- RELEASE_CAUSE
- PROCEDURE_TYPE
- SEID_CP
- SEID_UP
- SEQ_NO
- UP_IP_RESOURCE_INF_IP_ADDR
- UP_IP_RESOURCE_INF_TEID
- APPLICATION_INSTANCE_ID
- QER_CORRELATION_ID
- OFFENDING_IE
- DEST_INTERFACE
- FSEID_IP_ADDR_CP
- FSEID_IP_ADDR_UP
- NODE_ID_FQDN
- NODE_ID_IP
- NETWORK_NAME
- FQCSID_NODE_ADDR
- CSID
- MS_IP_ADDRESS
- FRAMES_COUNT
- TOTAL_BYTES_SEND_BY_MS
- TOTAL_BYTES_RECEIVED_BY_MS
- PROCEDURE_DURATION
- RECORD_DURATION
- START_TIME
- EVENT_TYPE
- SIGNALING_FILE_NAME
- SOURCE_IP
- DEST_IP
- SOURCE_NE_NAME
- DEST_NE_NAME
- FSEID_TEID_1
- FSEID_TEID_2
- FSEID_TEID_3
- FSEID_IP_1
- FSEID_IP_2
- FSEID_IP_3
- SERV_PRO_CORRELATION_ID
- IMSI
- IMEI
- APN
- MSISDN
- RAT_TYPE
- BEARER_QCI
- UNIQUE_CDR_ID
- VLAN_ID
- FRAMES_COUNT_SAVED
# primary_key: ''
table_name: CDR_PFCP
