columns:
- TARGET_CELL_ID
- TARGET_RNC_ID
- TARGET_C_ID
- MSG_COUNT
- CELL_ID
- DUPLICATE_MSG_COUNT
- CGI_COUNT
- CGI_LIST
- FIRST_CGI
- LAST_CGI_TIMESTAMP
- ORIG_PDD
- TERM_PDD
- HANDOVER_TYPE
- FIRST_LAC
- SERVING_CGI
- SERVING_PLMN_ID
- SERVING_LAC
- SERVING_SAC
- SERVING_CI
- SOURCE_CGI
- SOURCE_PLMN_ID
- SOURCE_LAC
- SOURCE_SAC
- SOURCE_RNC_ID
- REQUIRED_TARGET_CGI
- REQUIRED_TARGET_CELL_ID
- REQUIRED_TARGET_C_ID
- REQUIRED_TARGET_RNC_ID
- OLD_LAC
- OLD_RAC
- FIRST_SAC
- FIRST_CI
- FIRST_TARGET_CELL_ID
- FIRST_TARGET_C_ID
- FIRST_TARGET_RNC_ID
- RELOCATION_TYPE
- HANDOVER_CAUSE
- HANDOVER_REFERENCE
- INTERNAL_HANDOVER_RQD_COUNT
- HANDOVER_RQD_COUNT
- HANDOVER_PERFORMED_COUNT
- LOCATION_REPORT_COUNT
- RELOCATION_REQUIRED_COUNT
- INTEGRITY_PROTECTION_KEY
- CIPHERING_KEY
- PREFERED_CGI_LIST
- LAST_VISITED_CGI
- PAGING_PROCESS_DURATION
- AUTHENTICATION_CAUSE
- CELL_NAME
- CELL_REGION
- CLASSMARK_2_HEX
- CLASSMARK_3_HEX
- DEBUG_INFO
- DEST_NE_NAME
- DEVICE_TECHNOLOGY
- DROP_CAUSE
- IN_RTP_DEST_IP
- IN_RTP_DEST_IP_PORT
- FIRST_IU_PROCEDURE_TYPE
- IU_PROCEDURES_LIST
- MANUFACTURER
- MODEL
- NETWORK_NAME
- PAGING_BULK_COUNT
- RAT_TYPE
- RELEASE_CAUSE
- ROAMING_DIRECTION
- ROAMING_OPERATOR_NAME
- ROAMING_STATUS
- SETUP_CAUSE
- SOURCE_NE_NAME
- IN_RTP_SRC_IP
- IN_RTP_SRC_IP_PORT
- TAC_CATEGORY
- FRAMES_COUNT_SAVED
- START_HOUR
# primary_key: ''
table_name: CDR_IU_SCCP
