columns:
- TIME_STAMP
- MEASURING_PROBE_NAME
- SESSION_ID
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- SIGNALING_FILE_NAME
- SOURCE_IP
- DEST_IP
- MS_IP_ADDRESS
- GTP_TEID_DL
- GTP_TEID_UL
- ENB_UE_S1AP_ID
- MME_UE_S1AP_ID
- IMSI
- MSISDN
- MCC
- MNC
- IMEI
- APN
- BEARER_QCI
- CGI
- TAI_TAC
- TAC
- GUTI
- SERV_PRO_CORRELATION_ID
- RELEASE_CAUSE
- STMSI
- MANUFACTURER
- MODEL
- CELL_NAME
- ENB_NAME
- NETWORK_NAME
- MME_NAME
- SGW_NAME_USER_TRAFFIC
- APN_SERVICE
- TAC_CATEGORY
- CELL_REGION
- HANDOVER_TYPE
- PAGING_MESSAGE_COUNT
- RAT_TYPE_NAME
- SOURCE_NE_NAME
- DEST_NE_NAME
- PROCEDURE_SUBTYPE
- FRAMES_COUNT
- UNIQUE_CDR_ID
- RRC_ESTABLISHMENT_CAUSE
- S1AP_CAUSE
- NAS_EMM_CAUSE
- NAS_ESM_CAUSE
- GSM_SMS_CP_CAUSE
- GSM_SMS_RP_CAUSE
- GSM_SMS_TP_CAUSE
- SERIAL_NUMBER
- LCSAP_CORRELATION_ID
- RETAINABILITY_KPI
- ACCESSIBILITY_KPI
- MOBILITY_KPI
- RAT_TYPE
- FIRST_PROCEDURE_TYPE
- S1AP_PROCEDURES_LIST
- PAGING_BULK_COUNT
- GTP_TEID_UL_OLD
- GTP_TEID_DL_OLD
- TUNNEL_ID_CONTROL_UPLINK
- TUNNEL_ID_CONTROL_DOWNLINK
- TUNNEL_ID_DATA_UPLINK
- TUNNEL_ID_DATA_DOWNLINK
- S1AP_ENCRYPTED_ALGORITHM
- VLAN_ID
- RAT_TYPE_LIST
- FRAMES_COUNT_SAVED
table_name: CDR_S1AP
