columns:
- TIME_STAMP
- MEASURING_PROBE_NAME
- MEASURING_PROBE_TYPE
- SESSION_ID
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- IMSI
- MSISDN
- MS_IP_ADDRESS
- SIGNALING_FILE_NAME
- MEAN_THROUGHPUT_SENT
- MEAN_THROUGHPUT_RECEIVED
- TOTAL_BYTES_SEND_BY_MS
- TOTAL_BYTES_RECEIVED_BY_MS
- SERVICE_PORT
- GI_OVER_GN
- HOST_NAME
- TCP_RETRNSMT_BYTES_RATIO_DL
- TCP_RETRNSMT_BYTES_RATIO_UL
- IMEI
- RAT_TYPE
- CGI
- TAC
- INTERNET_LATENCY
- RAN_LATENCY
- TUNNEL_ID_DATA_UPLINK
- TUNNEL_ID_DATA_DOWNLINK
- SERV_PRO_CORRELATION_ID
- MANUFACTURER
- MODEL
- CELL_NAME
- MME_NAME
- SGW_NAME_USER_TRAFFIC
- PGW_NAME_USER_TRAFFIC
- SGSN_NAME_USER_TRAFFIC
- GGSN_NAME_USER_TRAFFIC
- APPLICATION_NAME
- SERVICE_DST_NAME
- RELEASE_CAUSE
- WEBSITE
- BEARER_QCI
- PROTOCOL
- APN_SERVICE
- TAC_CATEGORY
- CELL_REGION
- DEST_IP
- SOURCE_IP
- RAT_TYPE_NAME
- CHARGING_TYPE_NAME
- SOURCE_NE_NAME
- DEST_NE_NAME
- HANDOVER_INDICATION
- UNIQUE_CDR_ID
- TOTAL_DL_RAW_BYTES
- TOTAL_UL_RAW_BYTES
- GTP_INTERFACE_TYPE
- GTP_TEID_DL
- GTP_TEID_UL
- GTP_TEID_UL_OLD
- GTP_TEID_DL_OLD
- TUNNEL_ID_CONTROL_UPLINK
- TUNNEL_ID_CONTROL_DOWNLINK
- FRAMES_COUNT_SAVED
# primary_key: ''
table_name: CDR_GI
