columns:
- TIME_STAMP
- CDR_ID
- SESSION_ID
- MEASURING_PROBE_NAME
- START_TIME
- CALL_DURATION
- PDD
- ASR
- NER
- OUT_RTP_DEST_IP
- IN_RTP_DEST_IP
- SOURCE_IP_PORT
- DEST_IP_PORT
- SOURCE_IP
- DEST_IP
- SIGNALING_FILE_NAME
- SOURCE_ALIAS_FULL
- DEST_ALIAS_FULL
- SOURCE_PHONE_NUMBER
- DEST_PHONE_NUMBER
- CALL_TYPE
- VLAN_ID
- USER_AGENT
- RINGING_TIME
- CONNECTION_TIME
- DISCONNECTION_TIME
- MSG_COUNT
- EVENT_TYPE
- HOLD_CALL_COUNT
- MESSAGE_CONTENT_TYPE
- END_TIME
- RELEASE_CAUSE
- PROCEDURE_DURATION
- IN_RTP_DEST_IP_PORT
- OUT_RTP_DEST_IP_PORT
- CALLED_COUNTRY_CODE
- CALLING_COUNTRY_CODE
- CALLED_PARTY
- CALLING_PARTY
- CALL_ID
- PASSERTED
- DIVERSION
- SERV_PRO_CORRELATION_ID
- BWD_CONTACT_URI_USER
- BWD_CONTACT_URI_DOMAIN
- FWD_CONTACT_URI_USER
- FWD_CONTACT_URI_DOMAIN
- USER_AGENT_B
- P_ACCESS_NETWORK_INFO
- IMS_CHARGING_ID
- DSCP
- DIVERSION_REASON
- SIP_REASON
- IMSI
- MS_IP_ADDRESS
- CGI
- CORRELATION_CALL_ID
- PROCEDURE_TYPE
- MEDIA_TYPE
- SIGNALING_CODECS
- ORIGINATING_PATH
- TERMINATING_PATH
- SIP_REASON_PROTOCOL
- SIP_REASON_TEXT
- UNIQUE_CDR_ID
- MCPTT_GROUP_ID
- BYE_COUNT
- CANCEL_COUNT
- OPTIONS_COUNT
- PRACK_COUNT
- SUBSCRIBE_COUNT
- NOTIFY_COUNT
- PUBLISH_COUNT
- INFO_COUNT
- REFER_COUNT
- MESSAGE_COUNT
- UPDATE_COUNT
- REINVITE_COUNT
- SETUP_INVITE_COUNT
- SIP_RESPONSE_CODES
- RELEASE_DIRECTION
- SIP_1XX_COUNT
- SIP_2XX_COUNT
- SIP_3XX_COUNT
- SIP_4XX_COUNT
- SIP_5XX_COUNT
- SIP_6XX_COUNT
- SIP_BYE_RESPONSE_CODE
- SIP_CANCEL_RESPONSE_CODE
- SIP_OPTIONS_RESPONSE_CODE
- SIP_PRACK_RESPONSE_CODE
- SIP_SUBSCRIBE_RESPONSE_CODE
- SIP_NOTIFY_RESPONSE_CODE
- SIP_PUBLISH_RESPONSE_CODE
- SIP_INFO_RESPONSE_CODE
- SIP_REFER_RESPONSE_CODE
- SIP_MESSAGE_RESPONSE_CODE
- SIP_UPDATE_RESPONSE_CODE
- SIP_SETUP_INVITE_RESPONSE_CODE
- SIP_REINVITE_RESPONSE_CODE
- SOURCE_NE_NAME
- DEST_NE_NAME
- SIP_SESSION_ID
- MCPTT_PARTY_ID
- P_SERVED_USER
- RESOURCE_PRIORITY
- CPC
- CONVERSATIONID
- CONTRIBUTIONID
- IMDN_MESSAGE
- TMGI
- MC_SERVICE
- IN_PMOS_AVG
- OUT_PMOS_AVG
- IN_JITTER_AVG
- OUT_JITTER_AVG
- IN_PACKET_LOSS_AVG
- OUT_PACKET_LOSS_AVG
- IN_TOTAL_MUTE_COUNT
- OUT_TOTAL_MUTE_COUNT
- CORRELATION_SESSION_IDS
- IN_TOTAL_RTP_PACKETS
- OUT_TOTAL_RTP_PACKETS
- SRC_IMSI
- DST_IMSI
- MCPTT_SUBSCRIBER_ID
- SIP_EVENT_HEADER
- ACCESS_TYPE_NAME
- RAT_TYPE
- TERM_ACCESS_TYPE_NAME
- TERMINATING_CGI
- TMGI_HEX
- REVOKE_TYPE
- ROAMING_DIRECTION
- ROAMING_STATUS
- TERM_ROAMING_STATUS
- TERM_ROAMING_DIRECTION
- IN_HOLD_CALL_DURATION
- OUT_HOLD_CALL_DURATION
- IN_HOLD_CALL_COUNT
- OUT_HOLD_CALL_COUNT
- DEST_DSCP
- CARRIER_ID_CODE
- DROP_CALL_COUNT
- FRAMES_COUNT_SAVED
- LAST_RESPONSE_CAUSE
primary_key: CDR_ID
table_name: CDR_HPA_SIP
