columns:
- TIME_STAMP
- CDR_ID
- SESSION_ID
- START_TIME
- MEASURING_PROBE_NAME
- SIGNALING_FILE_NAME
- SOURCE_IP
- DEST_IP
- REGISTRATION_TYPE
- SOURCE_ALIAS_FULL
- DEST_ALIAS_FULL
- DEST_PHONE_NUMBER
- SOURCE_PHONE_NUMBER
- MSG_COUNT
- CALLING_PARTY
- RELEASE_CAUSE
- SERV_PRO_CORRELATION_ID
- SUBSCRIBER_IP_PORT
- DSCP
- USER_AGENT
- CALL_ID
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- CORRELATION_CALL_ID
- P_ACCESS_NETWORK_INFO
- CGI
- UNIQUE_CDR_ID
- REGISTER_COUNT
- CALLED_PARTY
- SIP_1XX_COUNT
- SIP_2XX_COUNT
- SIP_3XX_COUNT
- SIP_4XX_COUNT
- SIP_5XX_COUNT
- SIP_6XX_COUNT
- SIP_REGISTER_RESPONSE_CODE
- IMS_CHARGING_ID
- IMSI
- P_ASSOCIATED_URI
- ESP_ENCRYPTED_ALGORITHM
- DEST_DSCP
- FRAMES_COUNT_SAVED
primary_key: CDR_ID
table_name: CDR_SIP_REG
