columns:
- TIME_STAMP
- MEASURING_PROBE_LOC_ID
- PROBE_ID
- MEASURING_PROBE_NAME
- MEASURING_PROBE_TYPE
- QMANAGER_TIME_STAMP
- NUM_OF_TRANSACTIONS
- SESSION_ID
- START_TIME
- PROCEDURE_DURATION
- PROCEDURE_TYPE
- EVENT_TYPE
- END_CAUSE
- RELEASE_CAUSE
# - COUNTER
- SIGNALING_FILE_NAME
- SOURCE_IP
- DEST_IP
- SOURCE_NE_NAME
- DEST_NE_NAME
- BEARER_QCI
- NSSAI_SST
- NSSAI_SD
- INTERFACE
- SERVICE
- SERVICE_OPERATION
- HTTP_METHOD
- RESOURCE
- STREAM_ID
- IMSI
- IMEI
- SUPI
- SUCI
- MS_IP_ADDRESS
- MCC
- MNC
- MCC_MNC
- SERV_PRO_CORRELATION_ID
- RAT_TYPE
- FRAMES_COUNT
- UNIQUE_CDR_ID
- HTTP2_END_CAUSE
- NGAP_END_CAUSE
- NAS_5GSM_CAUSE
- APN
- MSISDN
- TRANSPORT_LAYER_ADDRESS_DL
- TRANSPORT_LAYER_ADDRESS_UL
- GTP_TEID_DL
- GTP_TEID_UL
- SERVICE_5G
- GPSI
- INTERNAL_GROUP_IDS
- VLAN_ID
- SOURCE_IP_PORT
- DEST_IP_PORT
- HPACK_TOTAL_DECOMPRESSION
- HPACK_FULLY_DECOMPRESSION
- HPACK_PARTIAL_DECOMPRESSION
- IMEI_SV
- AUTHORITY
- X_ENVOY_PEER_METADATA_ID
- RESOURCE_ID
- DEBUG_INFO
- URI
- ORIG_CALL_BACK_REF
- NOTIFICATION_URI
- RES
- RAND
- AUTN
- IMSI_CORRELATION_KEY
- INTERFACE_NAME
- SERVICE_5G_NAME
- SERVICE_OPERATION_NAME
- KASME
- TEID_AND_IP_LIST
- LOCATION_URI
- FRAMES_COUNT_SAVED
- END_CAUSE_FROM_JSON
- END_TIME
- SERVICE_SOURCE_PORT
- SERVICE_PORT
- NSSAI_SST_LIST
- NSSAI_SD_LIST
# primary_key: ''
table_name: CDR_HTTP2
