# orders.yaml
table_name: orders
primary_key: order_id  # Explicitly define the primary key
columns:
  - order_date
  - amount

foreign_keys:
  - column: user_id
    references:
      table: users
      column: user_id
    simulation:
      type: reference
      table: users
      column: user_id

  - column: products_id
    references:
      table: products
      column: products_id
    simulation:
      type: reference
      table: products
      column: products_id